source 'https://www.rubygems.org'

gem 'appium_lib',         '~> 6.0.0'
gem 'loofah'
gem 'nokogiri',           '~> 1.6.3.1'
gem 'rest-client'
gem 'rspec',              '~> 2.14.1'
gem 'cucumber',           '~> 2.4.0'
gem 'peach'
gem 'report_builder'
gem 'rspec-expectations', '~> 2.14.5'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.13'
gem 'test-unit',          '~> 2.5.5' # required for bundle exec ruby xunit_android.rb
gem 'json'
